---
# Update repository
- hosts: all
  tags: always
  become: true
  pre_tasks:
    - name: pre-run | update package cache (debian, etc)
      tags: always
      apt: update_cache=yes
      changed_when: False
      when: ansible_distribution == "Debian"

# Main run
#

# Cleanup repository
- hosts: all
  become: true
  tasks:
  - name: cleanup package cache
    tags: always
    apt:
      autoclean: yes
    changed_when: false
    when: ansible_distribution == "Debian"

  - name: autoremove orphan packages
    tags: always
    apt:
      autoremove: yes
      purge: yes
    when: ansible_distribution == "Debian"
  