---
- include_tasks: packages.yml

- include_tasks: software/flatpak.yml
- include_tasks: software/google_chrome.yml
- include_tasks: software/python.yml
- include_tasks: software/vscode.yml

- include_tasks: users/ansible.yml
- include_tasks: users/default.yml
- include_tasks: users/zsh.yml


- include_tasks: gnome/background.yml
- include_tasks: gnome/shell-settings.yml
- include_tasks: gnome/terminal.yml
