---
#
# User ansible
#
- name: user | ansible create group
  group:
    name: ansible
    system: yes
    state: present

- name: user | ansible create user
  user:
    name: ansible
    system: yes
    state: present
    shell: /bin/bash

- name: user | ansible authorized key
  authorized_key:
    user: ansible
    key: "{{ dvrg_ssh_key}}"
    state: present

- name: user | ansible sudoerd.d
  copy:
    src: sudo/ansible
    dest: /etc/sudoers.d/ansible
    owner: root
    group: root
    mode: 0660

#
# User {{ dvrg_user }}
#
# I like Zsh.
#
- name: user | install zsh
  apt:
    name:
      - zsh
      - zsh-syntax-highlighting
    state: latest
  when: ansible_distribution == "Debian"

- name: "user | {{ dvrg_user }} create group"
  group:
    name: "{{ dvrg_user }}"
    state: present

- name: "user | {{ dvrg_user }} create user"
  user:
    name: "{{ dvrg_user }}"
    group: "{{ dvrg_user }}"
    groups:
      - adm
      - audio
      - bluetooth
      - cdrom
      - dip
      - floppy
      - lpadmin
      - netdev
      - plugdev
      - scanner
      - sudo
      - video
    state: present
    comment: "{{ dvrg_comment }}"
    shell: /usr/bin/zsh

- name: "user | {{ dvrg_user }} authorized key"
  authorized_key:
    user: "{{ dvrg_user }}"
    key: "{{ dvrg_ssh_key}}"
    state: present

- name: user | {{ dvrg_user }} sudoerd.d
  copy:
    src: sudo/adm
    dest: /etc/sudoers.d/adm
    owner: root
    group: root
    mode: 0660
