---
packages:
  - apt-transport-https
  - curl
  - git
  - gnupg2
  - htop
  - neofetch
  - tmux
  - vim-nox

  - python3
  - python3-pip
  - python3-psutil
  - python3-venv
  - python3-wheel

  - task-gnome-desktop

  - mesa-utils
  - libgl1-mesa-glx
