---
- name: software | github-cli | add repository key
  apt_key:
    url: https://cli.github.com/packages/githubcli-archive-keyring.gpg
  when: ansible_distribution == "Debian"

- name: software | github-cli | add repository
  apt_repository:
    repo: deb [arch=amd64] https://cli.github.com/packages stable main
    filename: github-cli
  register:  github_cli_repo
  when: ansible_distribution == "Debian"

- name: software | github-cli | update sources (repo added or changed)
  apt:
    update_cache: yes
  changed_when: False
  when: github_cli_repo.changed

- name: software | github-cli | install package
  apt:
    name: gh
  when: ansible_distribution == "Debian"

- name: software | github-cli | zsh completion directory
  file:
    path: /usr/local/share/zsh/site-functions
    state: directory
    mode: 0755

- name: software | github-cli | zsh completion file exists
  stat:
    path: /usr/local/share/zsh/site-functions/_gh
  register: gh_completion_file
  changed_when: false
  ignore_errors: true

- name: software | github-cli | zsh completion file create
  shell: gh completion -s zsh
  register: gh_completion_output
  when: not gh_completion_file.stat.exists

- name: software | github-cli | zsh completion file save
  copy:
    content: "{{ gh_completion_output.stdout }}"
    dest: /usr/local/share/zsh/site-functions/_gh
    owner: root
    group: root
    mode: 0644
  when: not gh_completion_file.stat.exists
