---
- name: software | tor | add repository key
  apt_key:
    url: https://deb.torproject.org/torproject.org/A3C4F0F979CAA22CDBA8F512EE8CBC9E886DDD89.asc
  when: ansible_distribution == "Debian"

- name: software | tor | add repository
  apt_repository:
    repo: "deb [arch=amd64] https://deb.torproject.org/torproject.org {{ ansible_distribution_release }} main"
    filename: tor
  register: tor_repo
  when: ansible_distribution == "Debian"

- name: software | tor | update sources (repo added or changed)
  apt:
    update_cache: yes
  changed_when: False
  when: tor_repo.changed

- name: software | tor | install package
  apt:
    name: tor
  when: ansible_distribution == "Debian"
