---
- name: users ansible | create group
  group:
    name: ansible
    system: yes
    state: present

- name: users ansible | create user
  user:
    name: ansible
    system: yes
    state: present
    shell: /bin/bash

- name: users ansible | authorized key
  authorized_key:
    user: ansible
    key: "{{ dvrg_ssh_key}}"
    state: present

- name: users ansible | sudoerd.d
  copy:
    src: sudo/ansible
    dest: /etc/sudoers.d/ansible
    owner: root
    group: root
    mode: 0660

- name: users ansible | install ansible.service
  copy:
    src: systemd/ansible.service
    dest: /etc/systemd/system
    owner: root
    group: root
    mode: 0660

- name: users ansible | install ansible.timer
  copy:
    src: systemd/ansible.timer
    dest: /etc/systemd/system
    owner: root
    group: root
    mode: 0660

- name: users ansible | enable ansible.service
  systemd:
    name: ansible.service
    enabled: yes
    state: stopped

- name: users ansible | enable ansible.timer
  systemd:
    name: ansible.timer
    enabled: yes
    state: started
