---
- name: users ansible | create group
  group:
    name: ansible
    system: yes
    state: present

- name: users ansible | create user
  user:
    name: ansible
    system: yes
    state: present
    shell: /bin/bash

- name: users ansible | authorized key
  authorized_key:
    user: ansible
    key: "{{ dvrg_ssh_key}}"
    state: present

- name: users ansible | sudoerd.d
  copy:
    src: sudo/ansible
    dest: /etc/sudoers.d/ansible
    owner: root
    group: root
    mode: 0660
